### ISSUE TITLE
no automatic downloads

### ISSUE THREAD

**Issue by geraveoyomama** [crobibero/jellyfin-plugin-lrclib#13]
I installed v2 directly from the jellyfin repo, waited a day, manually started the task and lyrics dont show up automatically downloaded. Is this a feature already or am I misunderstanding?

**Comment by geraveoyomama** [comment]
For clarity, for each song I can manually download synced and not synced lyrics. My question is whether there is a toggle or feature to allow for automatic downloading.

**Comment by crobibero** [comment]
You need to complete a library scan after running the scheduled task.
