### ISSUE TITLE
Lyrics not being downloaded / no manual download option

### ISSUE THREAD

**Issue by pbogre** [crobibero/jellyfin-plugin-lrclib#3]
I just installed this plugin on my Jellyfin 10.9 server. First of all I see in the code that the settings should show 3 checkboxes, however in my settings I can only see the checkbox for strict search (the other 2 are briefly visible before disappearing).

I'm also not sure how this plugin is meant to be used. Is it supposed to automatically fetch lyrics for my music library? Because it's not doing that, and I also see no option to fetch lyrics manually for a given artist/album/track. Any help?

**Comment by crobibero** [comment]
I only tested with manual searching using Jellyfin's api, and forgot to hook lyrics into the rest of the functionality. 

As of right now Jellyfin only fully supports lyrics that are already available either embedded or next to the audio file. 

I may add a scheduled task to automatically download lyrics into the plugin as a temporary fix.

**Comment by pbogre** [comment]
Do you mean that you tested by finding lyrics that are already present in the tracks?

I can see in the code for this plugin that there is functionality to fetch lyrics, however it's not being called anywhere. Is this plugin something that is still WIP, or is there already a way to use it to fetch lyrics?

**Comment by crobibero** [comment]
The only way to search for remote lyrics right now is to manually hit Jellyfin's API.

**Comment by thomasdalberto** [comment]
Can you please explain better what do you mean by "manually hit Jellyfin's API"? how should it be done?

**Comment by Klar** [comment]
any update on this on how to search for lyrics and generate file?

**Comment by rom4nik** [comment]
> Can you please explain better what do you mean by "manually hit Jellyfin's API"? how should it be done?

You can do this with 2 requests per song, e.g. via curl or browser devtools (I used "edit and resend" in Firefox to quickly borrow `Authentication` header from one of other requests frontend sends to client).

1. https://api.jellyfin.org/#tag/Lyrics/operation/SearchRemoteLyrics

`GET /Audio/{itemId}/RemoteSearch/Lyrics`

This will return available lyrics from all enabled lyrics providers (which in my case was only LrcLib), for example:

```json
[
  {
    "Id": "a1da397dd09c89a18bacecb3a5d45d37_984710_synced",
    "ProviderName": "LrcLib",
    "Lyrics": {
      "Metadata": {
        "Artist": "Two Feet",
        "Album": "A 20 Something Fuck",
        "Title": "I Feel Like I'm Drowning",
        "Length": 1860000000,
        "IsSynced": true
      },
      "Lyrics": [
        {
          "Text": "You keep dreamin' and dark schemin'",
          "Start": 132000000
        },
        {
          "Text": "Yeah, you do",
          "Start": 166800000
        },
[...]
      ]
    }
  },
  {
    "Id": "a1da397dd09c89a18bacecb3a5d45d37_984710_plain",
    "ProviderName": "LrcLib",
    "Lyrics": {
      "Metadata": {
        "Artist": "Two Feet",
        "Album": "A 20 Something Fuck",
        "Title": "I Feel Like I'm Drowning",
        "Length": 1860000000,
        "IsSynced": false
      },
      "Lyrics": [
        {
          "Text": "You keep dreamin' and dark schemin'"
        },
        {
          "Text": "Yeah, you do"
        },
[...]
      ]
    }
  }
]
```

2. https://api.jellyfin.org/#tag/Lyrics/operation/DownloadRemoteLyrics

`POST /Audio/{itemId}/RemoteSearch/Lyrics/{lyricId}`

This downloads lyrics, saves them to server and also returns them in HTTP response.

**Comment by GlassedSilver** [comment]
Yeah, I think I'm waiting for the plugin to get a scheduled task. 😅

**Comment by crobibero** [comment]
Adding the scheduled task in https://github.com/crobibero/jellyfin-plugin-lrclib/pull/4

Feel free to test, it is pretty basic and not really configurable.

**Comment by Krafting** [comment]
> Adding the scheduled task in #4
> 
> Feel free to test, it is pretty basic and not really configurable.

Thank you reaally much for your work ! 

Do you think it will be possible, in the future, to add a button to fetch lyrics for a specific song only (for example in the right click menu, and also something for Apps like Finamp to be able to fetch lyrics using this plugin), and not only get all the lyrics of all the tracks in your library ?

**Comment by crobibero** [comment]
>Do you think it will be possible, in the future, to add a button to fetch lyrics for a specific song only 

Yes, but that would be built into the server and not this plugin.

**Comment by ShakedBaws** [comment]
> Adding the scheduled task in #4
> 
> Feel free to test, it is pretty basic and not really configurable.

mind explaining how to get this to work ?
also a download lyrics button would be really appreciated !

**Comment by ShakedBaws** [comment]
> Adding the scheduled task in #4
> 
> Feel free to test, it is pretty basic and not really configurable.

thank you for this plugin . 
can you please explain how to use it on the github page?
also would be really appreciated if you can add a button to fetch lyrics for current song or fetch lyrics for all liked songs.
thank you in advanced.

**Comment by crobibero** [comment]
1. Build and install the plugin
2. Run the scheduled task
3. Perform library scan

**Comment by ShakedBaws** [comment]
im sorry I never had to run scheduled task before
I went to the " scheduled task" section in jellyfin but I don't see anything related to lyrics .
maybe I missed it or am I doing something wrong?

**Comment by GlassedSilver** [comment]
> im sorry I never had to run scheduled task before I went to the " scheduled task" section in jellyfin but I don't see anything related to lyrics . maybe I missed it or am I doing something wrong?

I'm gonna take a wild guess here and respectfully assume you're probably not a developer and hence didn't build the plugin yourself and installed it manually instead of the current release available through the standard procedure.

If that's the case it's probably best for you to just wait a little bit for the new version with the added functionality to release, probably not too far away now.

**Comment by peter9teufel** [comment]
Hi, is there an ETA for the next release that includes the scheduled job? Setting everything up to build the plugin myself would not be a great hassle as I am a developer but won't be worth the effort if the next release is around the corner 😄 

Thanks for your work and best regards,
Peter

**Comment by Felitendo** [comment]
Any updates? @crobibero

**Comment by crobibero** [comment]
I am not planning on releasing the plugin with the scheduled task built in. If you want it you will need to build it yourself. The task will exist for Jellyfin 10.10

**Comment by Felitendo** [comment]
> I am not planning on releasing the plugin with the scheduled task built in. If you want it you will need to build it yourself. The task will exist for Jellyfin 10.10

I tried really hard to build it myself, but it just said "Status: Not Supported"

**Comment by Felitendo** [comment]
> I am not planning on releasing the plugin with the scheduled task built in. If you want it you will need to build it yourself. The task will exist for Jellyfin 10.10

And what do you mean by "The Task will exist for Jellyfin 10.10

**Comment by Felitendo** [comment]
@crobibero

**Comment by Felitendo** [comment]
Hey everyone. I got it working :D

You need to do the following:

1. Make sure your Jellyfin server is updated to **version 10.11.0 or higher**
2. Add the plugin repository URL to Jellyfin:
   ```
   https://raw.githubusercontent.com/Felitendo/jellyfin-plugin-lyrics/master/manifest.json
   ```
4. Open the **Plugin Catalog** in your Jellyfin dashboard  
5. Look for **"Lyrics"** under the **Metadata** category and install it
6. Restart Jellyfin
7. Search for the Plugin "LrcLib" (is sometimes pre-installed) and uninstall it (if it's not installed then skip this step)
8. Restart Jellyfin again
9. Go to **Scheduled Tasks** and run **"Download missing lyrics (new)"**
10. Go to **Libraries** and click on **Scan all Libraries**

You can find the source code and ask for help here: https://github.com/Felitendo/jellyfin-plugin-lyrics

Hope this helps :)

**Comment by TechnicallyMay** [comment]
@Felitendo thank you so much! I'll give this a try soon.

**Comment by thecodygriffin** [comment]
For anyone else who may be installing from @Felitendo's repository, make sure you have upgraded to 10.9.10. The plug-in was initially unsupported for me as I was still on 10.9.7.

**Comment by zidgeZ** [comment]
@Felitendo Thank you very much, it works very well on my end! As what @thecodygriffin said, Jellyfin should definitely be upgraded to 10.9.10 as I've tried it on 10.9.9 and it didn't work.

**Comment by nechodom** [comment]
Hi, I installed your version @Felitendo, but i cannot see any option "Download missing lyrics". Here´s screenshot of my page. I have installed newest version of Jellyfin.

Thanks for help!
![image](https://github.com/user-attachments/assets/e39d9c60-f520-49a5-834f-7963fbb8a44b)

**Comment by TannerNelson16** [comment]
I tried both manually building the plugin and using @Felitendo 's repository and I can't get scheduled task to show up. I am on Jellyfin 10.9.11 if that affects anything. Any advice?

**Comment by pollocluck** [comment]
> I tried both manually building the plugin and using @Felitendo 's repository and I can't get scheduled task to show up. I am on Jellyfin 10.9.11 if that affects anything. Any advice?

I second this. Any updates on this, @Felitendo?

**Comment by Felitendo** [comment]
> > I tried both manually building the plugin and using @Felitendo 's repository and I can't get scheduled task to show up. I am on Jellyfin 10.9.11 if that affects anything. Any advice?
> 
> I second this. Any updates on this, @Felitendo?

I'm sorry that it doesn't work right now. I would need to test that and figure out how to update it to 10.9.11. I will try to fix it on Sunday (04.10.2024). If anyone knows what the issue could be or knows how to update it to 10.9.11, a pull request would be greatly appreciated :)

**Comment by Felitendo** [comment]
I'm sorry that it doesn't work for you @TannerNelson16 and @pollocluck.
I have tried it on a fresh install of Jellyfin 10.9.11 today and it works just fine.
If you still need help then you can add me on Discord: @Felitendo
Or create a Support Ticket on my Discord Server: https://dsc.gg/felitendo

**Comment by pollocluck** [comment]
I can confirm the downloads are now working on the public version of Finamp. Thank you so much @Felitendo !

**Comment by EsmailELBoBDev2** [comment]
> Hey everyone. I got it working :D
> 
> You need to do the following:
> 
> 1. Update your Jellyfin to 10.9.10 or above
> 2. Add my Plugin's repository to Jellyfin: https://raw.githubusercontent.com/Felitendo/jellyfin-lyrics-plugin/master/manifest.json
> 3. Go into your Plugin Catalog and install "LrcLib", it should be under "Notifications"
> 4. Go into Sceduled Tasks and run "Download missing lyrics"
> 5. Go into Librarys and then press "Scan all Librarys"
> 6. Now the Lyrics should work. If they don't then you need to go to your Album -> Right click -> "Refresh metadata"
> 
> You can find the source code and ask for help here: https://github.com/Felitendo/jellyfin-lyrics-plugin
> 
> Hope this helps :)

Hello I just installed this by sadly I can't find 'Download missing lyrics' in tasks...

**Comment by Felitendo** [comment]
> > Hey everyone. I got it working :D
> > You need to do the following:
> > 
> > 1. Update your Jellyfin to 10.9.10 or above
> > 2. Add my Plugin's repository to Jellyfin: https://raw.githubusercontent.com/Felitendo/jellyfin-lyrics-plugin/master/manifest.json
> > 3. Go into your Plugin Catalog and install "LrcLib", it should be under "Notifications"
> > 4. Go into Sceduled Tasks and run "Download missing lyrics"
> > 5. Go into Librarys and then press "Scan all Librarys"
> > 6. Now the Lyrics should work. If they don't then you need to go to your Album -> Right click -> "Refresh metadata"
> > 
> > You can find the source code and ask for help here: https://github.com/Felitendo/jellyfin-lyrics-plugin
> > Hope this helps :)
> 
> Hello I just installed this *but sadly I can't find 'Download missing lyrics' in tasks...I'm using 10.9.11 too but not so fresh install if being honest, it runs for some weeks now

Please create an issue here: https://github.com/Felitendo/jellyfin-lyrics-plugin/issues

**Comment by Felitendo** [comment]
> > Hey everyone. I got it working :D
> > You need to do the following:
> > 
> > 1. Update your Jellyfin to 10.9.10 or above
> > 2. Add my Plugin's repository to Jellyfin: https://raw.githubusercontent.com/Felitendo/jellyfin-lyrics-plugin/master/manifest.json
> > 3. Go into your Plugin Catalog and install "LrcLib", it should be under "Notifications"
> > 4. Go into Sceduled Tasks and run "Download missing lyrics"
> > 5. Go into Librarys and then press "Scan all Librarys"
> > 6. Now the Lyrics should work. If they don't then you need to go to your Album -> Right click -> "Refresh metadata"
> > 
> > You can find the source code and ask for help here: https://github.com/Felitendo/jellyfin-lyrics-plugin
> > Hope this helps :)
> 
> Hello I just installed this *but sadly I can't find 'Download missing lyrics' in tasks...I'm using 10.9.11 too but not so fresh install if being honest, it runs for some weeks now

https://github.com/Felitendo/jellyfin-lyrics-plugin/issues/2

**Comment by crobibero** [comment]
Jellyfin 10.10 is now released so automatic lyric downloading is built-in.

**Comment by Felitendo** [comment]
> Jellyfin 10.10 is now released so automatic lyric downloading is built-in.

Is it a setting somewhere in jellyfin and if so what is it called and how can we use it? (If it has the exact same features as my fork then I'm going to deprecate it)

**Comment by crobibero** [comment]
Yes, it has the same features as the original PR that I had created to add the scheduled task.
